# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: heap-helpers 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "heap-helpers"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Victor Costan"]
  s.date = "2016-02-26"
  s.description = "Rails-compatible helpers for setting the heap.js snippet"
  s.email = "victor@costan.us"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile187",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "heap-helpers.gemspec",
    "lib/heap-helpers.rb",
    "lib/heap-helpers/client.rb",
    "lib/heap-helpers/helpers.rb",
    "lib/heap-helpers/snippet.js",
    "test/client_test.rb",
    "test/heap_test.rb",
    "test/helper.rb",
    "test/tags_test.rb"
  ]
  s.homepage = "http://github.com/pwnall/heap-helpers-ruby"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Heap javascript snippet helpers"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<heap>, ["~> 1.0"])
      s.add_development_dependency(%q<activesupport>, [">= 2.3.8"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0.8.7.6"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1"])
    else
      s.add_dependency(%q<heap>, ["~> 1.0"])
      s.add_dependency(%q<activesupport>, [">= 2.3.8"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0.8.7.6"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1"])
    end
  else
    s.add_dependency(%q<heap>, ["~> 1.0"])
    s.add_dependency(%q<activesupport>, [">= 2.3.8"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0.8.7.6"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1"])
  end
end

